name: iBukkit
version: D 4.0-DEV
description: The new Util project
#Cherry is the name of the version kind of like andriods system ex. Android Lollipop
authors: [buildcarter8, babybreezy]
main: me.buildcarter8.iBukkit.Main
commands:
 ibukkit:
    description: plugin info
    aliases: ib
 getip:
    description: ip address
