name: iBukkit
version: Cherry 3.1
description: The new Util project
#Cherry is the name of the version kind of like andriods system ex. Android Lollipop
author: buildcarter8
main: me.buildcarter8.iBukkit.Main
commands:
 ibukkit:
    description: plugin info
    aliases: ib
 getip:
    description: ip address
